CREATE TABLE  HOTELS(
HOTEL_SNO INT PRIMARY KEY,
HOTEL_NAME VARCHAR (50),
HOTEL_PLACE VARCHAR (30),
HOTEL_DEPT VARCHAR (40),
HOTEL_STATE VARCHAR (20),
HOTEL_AGE INT,
);

INSERT INTO HOTELS (HOTEL_SNO,HOTEL_NAME,HOTEL_PLACE,HOTEL_DEPT,HOTEL_STATE,HOTEL_AGE)
VALUES
(1,'SHADHAB','HITECH CITY','BIRYANI','TELANGANA',10),
(2,'MEFHIL','PARADISE','ROTI','AP',20),
(3,'PARADISE','KUKATPALLY','BIRYANI','MP',4),
(4,'SHAGOUSE','AMMERPET','CHICKEN','MK',5),
(5,'UDIPI','SR NAGAR','SAMBAR','UP',6);

SELECT *FROM HOTELS

SELECT 
AVG(HOTEL_AGE) AS AVG_AGE,
MAX(HOTEL_AGE) AS MAX_AGE,
MIN(HOTEL_AGE) AS MIN_AGE,
SUM(HOTEL_AGE) AS TOTAL_AGE,
COUNT(*) AS TOTAL_HOTELS
FROM HOTELS;

SELECT *FROM HOTELS;

SELECT HOTEL_DEPT,
AVG(HOTEL_AGE) AS avg_age,
COUNT(HOTEL_SNO) AS TOTAL_HOTELS
FROM HOTELS
GROUP BY HOTEL_DEPT;

SELECT *FROM HOTELS;

SELECT HOTEL_DEPT,
AVG(HOTEL_AGE) AS avg_age,
COUNT(HOTEL_SNO) AS TOTAL_HOTELS
FROM HOTELS
GROUP BY HOTEL_DEPT
HAVING AVG(HOTEL_AGE) >5;

SELECT *FROM HOTELS;



