CREATE TABLE WORKERS(
WORKER_ID INT PRIMARY KEY,
WORKER_NAME VARCHAR(49),
WORKER_DEPT VARCHAR(30),
WORKER_AGE INT,
WORKER_PLACE VARCHAR(50));


 INSERT INTO WORKERS(WORKER_ID,WORKER_NAME,WORKER_DEPT,WORKER_PLACE)
 VALUES
(1,'PRASHU','MECH','BHPL'),
(2,'JESHU','CIVIL','KNR'),
(3,'RAJ','EEE','NNN'),
(4,'kkk','mng','MKN'),
(5,'JKH','FEE','ERE');

SELECT *FROM WOERKERS;

SELECT *FROM WORKERS  WHERE WORKER_ID=1;

 SELECT *FROM WORKERS WHERE WORKER_PLACE = 'BHPL' AND WORKER_ID >= 1;

 SELECT *FROM WORKERS WHERE WORKER_PLACE ='BHPL' OR WORKER_PLACE='ERE';

 SELECT *FROM WORKERS WHERE WORKER_NAME = 'PRASHU' OR WORKER_ID <= 2;

 SELECT *FROM WORKERS WHERE WORKER_ID BETWEEN 2 AND  4;

 SELECT *FROM WORKERS WHERE WORKER_NAME LIKE 'J%';

 SELECT *FROM WORKERS ORDER BY WORKER_ID DESC;

 SELECT *FROM WORKERS ORDER BY WORKER_ID ASC;

 SELECT *FROM WORKERS;

 

